version: '3.8'

networks:
  plugmart-network:
    driver: bridge

services:

  # =========================
  # DATABASES
  # =========================

  postgres-order:
    image: postgres:15
    container_name: postgres-order
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    networks:
      - plugmart-network

  postgres-inventory:
    image: postgres:15
    container_name: postgres-inventory
    environment:
      POSTGRES_DB: inventorydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    networks:
      - plugmart-network

  mongo:
    image: mongo:7.0
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - plugmart-network


  # =========================
  # KAFKA
  # =========================

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - plugmart-network

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT_INTERNAL
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INTERNAL://broker:29092
      KAFKA_LISTENERS: PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - plugmart-network


  # =========================
  # OBSERVABILITY
  # =========================

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - plugmart-network


  # =========================
  # SERVICE DISCOVERY
  # =========================

  discovery-server:
    image: ben1309/discovery-server:latest
    container_name: discovery-server
    ports:
      - "8761:8761"
    networks:
      - plugmart-network


  # =========================
  # MICROSERVICES
  # =========================

  inventory-service:
    image: ben1309/inventory-service:latest
    container_name: inventory-service
    depends_on:
      - discovery-server
      - postgres-inventory
      - broker
    ports:
      - "8182:8182"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-inventory:5432/inventorydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_KAFKA_BOOTSTRAP_SERVERS: broker:29092
    networks:
      - plugmart-network


  order-service:
    image: ben1309/order-service:latest
    container_name: order-service
    depends_on:
      - discovery-server
      - postgres-order
      - broker
    ports:
      - "8183:8183"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-order:5432/orderdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_KAFKA_BOOTSTRAP_SERVERS: broker:29092
    networks:
      - plugmart-network


  product-service:
    image: ben1309/product-service:latest
    container_name: product-service
    depends_on:
      - discovery-server
      - mongo
    ports:
      - "8184:8184"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/productdb
    networks:
      - plugmart-network


  notification-service:
    image: ben1309/notification-service:latest
    container_name: notification-service
    depends_on:
      - discovery-server
      - broker
    ports:
      - "8185:8185"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka
      SPRING_KAFKA_BOOTSTRAP_SERVERS: broker:29092
    networks:
      - plugmart-network


  api-gateway:
    image: ben1309/api-gateway:latest
    container_name: api-gateway
    depends_on:
      - discovery-server
    ports:
      - "8888:8888"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka
    networks:
      - plugmart-network
